/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LongTermImport } from './routes/long-term'
import { Route as DoneImport } from './routes/done'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LongTermRoute = LongTermImport.update({
  path: '/long-term',
  getParentRoute: () => rootRoute,
} as any)

const DoneRoute = DoneImport.update({
  path: '/done',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/done': {
      preLoaderRoute: typeof DoneImport
      parentRoute: typeof rootRoute
    }
    '/long-term': {
      preLoaderRoute: typeof LongTermImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  DoneRoute,
  LongTermRoute,
])

/* prettier-ignore-end */
